name: Python CI

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:

  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        name: Checkout my project
      - name: Install Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"
      - name: Install requirements
        run: |
          python -m pip install -r requirements.txt
          pip install pylint
          pip install coverage
      - name: Analysing the code with pylint
        run: |
          pylint application/ tests/ --exit-zero
      - name: run coverage
        run: |
          coverage run -m pytest --profile
      - name: run locust
        run: |
          locust --config=.locust.conf